solve the issue no #1900 follow line remove world duplicates
JdeRobot/RoboticsAcademy pull request #1909
Opened 2023-01-27 12:21 UTC by GauravKumar9920

I have Updated the game launch files and added the robot spawn environment directly into the launch file while replacing the game wold by classic world env.

2023-01-30 12:11 UTC, pariaspe requested changes
Spawn urdf node is well used, but what is "baxter"? 
Also, include in your PR the 4 game world files removed

2023-01-30 18:29 UTC, GauravKumar9920 commented
> Spawn urdf node is well used, but what is "baxter"? Also, include in your PR the 4 game world files removed

Thanks @pariaspe for taking a look into the PR :)
I will remove the files, about the Baxter the code for launching the bot into the environment was provided in the issue page itself if you recommend changes to it can you suggest some replacement to the code for the same.

2023-01-31 08:32 UTC, pariaspe commented
> I will remove the files, about the Baxter the code for launching the bot into the environment was provided in the issue page itself if you recommend changes to it can you suggest some replacement to the code for the same.

Sorry, I haven't been descriptive enough. You have to spawn the model we are not including in the world, *f1_guest* model.

2023-02-01 15:26 UTC, GauravKumar9920 commented
@pariaspe I have updated the code in response with the previous issue kindly have a look.

2023-02-03 16:02 UTC, pariaspe requested changes
Hi, I've tested your solution. The f1_guest is spawning correctly, but you have to set it the right position. To do that, give the position by adding the options `-x 0 -y 0 -z 1` to the node in the launch file. Thanks!

![default_gzclient_camera(1)-2023-02-03T16_55_33 323914](https://user-images.githubusercontent.com/35956525/216648645-ef783310-c17e-42ff-b570-90e6b640b5a1.jpg)

2023-02-04 17:29 UTC, pariaspe commented
Hey, some more things:
- We usually do one PR per issue. I understand that issue #1910 is quite close related to this one, but please undo last commit ([262fc30](https://github.com/JdeRobot/RoboticsAcademy/pull/1909/commits/262fc3055137faec76a11bfcfc47c90fbaefa62a)) and open a PR with those changes.
- You are not using correctly spawn args. Check its help:
```bash
$ rosrun gazebo_ros spawn_model --help
usage: spawn_model [-h] (-urdf | -sdf)
                   (-file FILE_NAME | -param PARAM_NAME | -database MODEL_NAME | -stdin)
                   -model MODEL_NAME [-reference_frame REFERENCE_FRAME]
                   [-gazebo_namespace GAZEBO_NAMESPACE]
                   [-robot_namespace ROBOT_NAMESPACE] [-unpause]
                   [-wait MODEL_NAME] [-x X] [-y Y] [-z Z] [-R R] [-P P]
                   [-Y Y] [-J JOINT_NAME JOINT_POSITION] [-package_to_model]
                   [-b]

Spawn a model in gazebo using the ROS API

optional arguments:
  -h, --help            show this help message and exit
  -urdf                 Incoming xml is in urdf format
  -sdf                  Incoming xml is in sdf format
  -file FILE_NAME       Load model xml from file
  -param PARAM_NAME     Load model xml from ROS parameter
  -database MODEL_NAME  Load model XML from specified model in Gazebo Model
                        Database
  -stdin                Load model from stdin
  -model MODEL_NAME     Name of model to spawn
  -reference_frame REFERENCE_FRAME
                        Name of the model/body where initial pose is defined.
                        If left empty or specified as "world", gazebo world
                        frame is used
  -gazebo_namespace GAZEBO_NAMESPACE
                        ROS namespace of gazebo offered ROS interfaces.
                        Defaults to /gazebo/
  -robot_namespace ROBOT_NAMESPACE
                        change ROS namespace of gazebo-plugins
  -unpause              !!!Experimental!!! unpause physics after spawning
                        model
  -wait MODEL_NAME      !!!Experimental!!! wait for model to exist
  -x X                  x component of initial position, meters
  -y Y                  y component of initial position, meters
  -z Z                  z component of initial position, meters
  -R R                  roll angle of initial orientation, radians
  -P P                  pitch angle of initial orientation, radians
  -Y Y                  yaw angle of initial orientation, radians
  -J JOINT_NAME JOINT_POSITION
                        initialize the specified joint at the specified
                        position
  -package_to_model     convert urdf <mesh filename="package://..." to <mesh
                        filename="model://..."
  -b                    bond to gazebo and delete the model when this program
                        is interrupted
```
And see what you are doing:
```xml
<node name="spawn_f1_guest_sdf" pkg="gazebo_ros" type="spawn_model" args="-file $(find CustomRobots)/f1/f1_guest/model.sdf -sdf -z 1 -model model" -x 0 -y 0 -z 1 -Y 0 />  <!-- bad, args out of string -->
<!-- Try something more like -->
<node name="spawn_f1_guest_sdf" pkg="gazebo_ros" type="spawn_model" args="-file $(find CustomRobots)/f1/f1_guest/model.sdf -sdf -x 0 -y 0 -z 1 -Y 0 -model model"/>
```
Besides, the 0 x pose, 0 y pose and 0 yaw is not the desired ones. You can check the good ones in the old world files were replacing with this spawns.

2023-02-04 18:30 UTC, GauravKumar9920 commented
Hey, apologies from my side regarding this, I haven't  been able to set up a testing environment due to which these issues are taking place, I am working on it and I will make sure from now onward to not commit something without testing. Also am reverting the last commit.

2023-02-09 07:49 UTC, GauravKumar9920 commented
@pariaspe kindly check the PR.

2023-02-10 15:41 UTC, pariaspe requested changes
Hey, some final comments:
- You are spawning both f1 at the same pose. Check the old worlds files again, since they don't have the same position.
- With `-model model` argument you are setting the model name. Change it to use something more descriptive, like `-model f1_guest`.

2023-02-15 08:59 UTC, pariaspe requested changes

2023-02-15 08:59 UTC, pariaspe commented on exercises/static/exercises/follow_line/web-template/launch/simple_line_follower_game_ros_headless_default.launch
> +  <node name="spawn_f1_guest_sdf" pkg="gazebo_ros" type="spawn_model" args="-file $(find CustomRobots)/f1/f1_guest/model.sdf -sdf -x 53.2 -y -6.8 -z 0.004 -R 0 -P 0 -Y -4.85 -model f1_guest"/>
Hey, the very last changes. `x`should be -53.2 instead of 53.2 (negative sign)

2023-02-15 10:51 UTC, pariaspe approved these changes

2023-02-15 10:52 UTC, merged

2023-02-15 10:52 UTC, pariaspe commented
Nice job @GauravKumar9920 !