Fix: Issue 2551
JdeRobot/RoboticsAcademy pull request #2595
Opened 2024-06-23 17:43 UTC by Apoorvgarg-creator

Fix #2551

2024-06-23 20:02 UTC, pawanw17 commented on exercises/templates/exercises/vacuum_cleaner_loc_newmanager/exercise.html
> +    {% react_component exercise/vacuum_cleaner__loc_newmanager/BasicVacuumCleaner %}
Is that a typo?

2024-06-24 05:47 UTC, javizqh requested changes
It still happens

https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/6f756b7e-8b7e-4ffa-a47f-93a3290fb097

2024-06-24 05:50 UTC, Apoorvgarg-creator commented
@javizqh Looking into this

2024-06-24 05:56 UTC, javizqh commented
Yes, that dot should not appear

2024-06-24 05:56 UTC, javizqh commented
Everything else is correct, is just the dot that appears at the last position of the last execution

2024-07-01 20:36 UTC, Apoorvgarg-creator commented
Whenever I try to run any solution I get this error.


<img width="1440" alt="Screenshot 2024-07-02 at 2 06 09 AM" src="https://github.com/JdeRobot/RoboticsAcademy/assets/57873504/a2259db5-bb71-4d8b-a412-55722c261a1c">

2024-07-01 20:36 UTC, Apoorvgarg-creator commented
@javizqh Can you please test the changes

2024-07-01 20:52 UTC, javizqh requested changes
Sadly it still happens. Use this code to test it, to see if for you it works OK:
``` python
import GUI
import HAL
# Enter sequential code!

angular_speed = 0.3
linear_speed = 0.2
i = 0

while True:
    HAL.setV(linear_speed)
    HAL.setW(angular_speed)
    i = i + 1
```

2024-07-02 15:01 UTC, Apoorvgarg-creator commented
Demo Video to show the PR works.

https://github.com/JdeRobot/RoboticsAcademy/assets/57873504/2fb23383-e09b-4543-b0fe-6503af45e5f2

@javizqh

2024-07-02 15:09 UTC, javizqh approved these changes
Works perfectly

2024-07-02 15:09 UTC, merged